// src/lib/cards.ts
import type { Card } from '@/store/gameStore'

export const cards: Card[] = [
  { id: 1, name: "Кринжовые истории на балконе", type: "story", isStory: true, cring: 8, mental: 6 },
  { id: 2, name: "Пакет Изабеллы", type: "active", mental: 4, onTurnStart: (s) => { s.opponent.cring += 1 } },
  { id: 3, name: "Чей-то друг", type: "active", onTurnStart: (s) => { s.me.mental += 2 } },
  { id: 4, name: "Зашиперили", type: "normal", cring: 12, effect: (s) => { if (s.opponent.field.some(c => c.id === 3)) s.opponent.cring += 8 } },
  { id: 5, name: "Догон", type: "instant", effect: (s) => { s.me.field = []; s.opponent.field = []; s.me.mental += 20; s.opponent.skippedTurn = true } },
  { id: 6, name: "Слеза утконоса", type: "normal", effect: (s) => { const dmg = s.me.field.some(c => c.id === 3) || s.opponent.field.some(c => c.id === 3) ? 10 : 25; s.me.cring += dmg; s.opponent.cring += dmg; s.me.field = s.me.field.filter(c => c.id !== 3); s.opponent.field = s.opponent.field.filter(c => c.id !== 3) } },
  { id: 7, name: "Закрытый туалет", type: "active", onTurnStart: (s) => { s.opponent.cring += 1 + s.opponent.field.filter(c => c.id === 7).length } },
  { id: 8, name: "Выломать дверь", type: "instant", effect: (s) => { s.opponent.field = s.opponent.field.filter(c => c.id !== 7); s.doorKicked = true } },
  { id: 9, name: "Блейза", type: "normal", effect: (s) => { Math.random() < 0.5 ? s.opponent.cring += 18 : s.me.mental += 18 } },
  { id: 10, name: "Поправил пипирку и поймал взгляд бабки", type: "normal", effect: (s) => { s.me.field.some(c => c.id === 1) ? (s.opponent.cring += 6, s.me.mental += 12) : s.me.mental += 8 } },
  { id: 11, name: "Пукнул в тихую, но обосрался", type: "active", onTurnStart: (s) => { if (!s.opponent.field.some(c => c.id === 7)) s.opponent.cring += 3 } },
  { id: 12, name: "Заглянуть не туда", type: "normal", effect: (s) => { s.me.cring += 6; s.me.mental += 3 } },
  { id: 13, name: "Дикий зверь", type: "story", isStory: true, effect: (s) => { s.opponent.cring += 3 + s.storiesPlayed * 3 } },
  { id: 14, name: "Блять, кто это сделал?", type: "story", isStory: true, effect: (s) => { const base = Math.floor(Math.random() * 7) + 4; s.opponent.cring += s.doorKicked ? base * 2 : base } },
  { id: 15, name: "Слава роду", type: "normal", effect: () => { console.log("Слава роду!") } }, // эффект в drawCard
  { id: 16, name: "Харкнуть в глаз", type: "normal", effect: (s) => { s.opponent.cring += 20 + (s.opponent.field.some(c => c.id === 7) ? 15 : 0) } },
  { id: 17, name: "Собрать всех и не придти", type: "normal", cring: 15, mental: 20 },
  { id: 18, name: "Пёс", type: "active", onTurnStart: (s) => { if (s.opponent.field.some(c => c.id === 19)) s.opponent.cring += 10 } },
  { id: 19, name: "Азиатские ножки", type: "active", onTurnStart: (s) => { s.me.mental += 5 } },
  { id: 20, name: "Хозяин хаты", type: "normal", effect: (s) => { Math.random() < 0.5 ? (s.opponent.cring += 15, setTimeout(() => s.opponent.cring += 30, 4000)) : (s.me.mental += 5, setTimeout(() => s.me.mental += 35, 4000)) } },
  { id: 21, name: "Туалет для инвалидов", type: "story", isStory: true, cring: 16 },
  { id: 22, name: "Красные глаза", type: "active", isStory: true, onTurnStart: (s) => { s.opponent.cring += 1 + s.me.field.filter(c => c.id === 22).length } },
  { id: 23, name: "Контрастный душ", type: "instant", mental: 8, effect: (s) => { s.opponent.field = s.opponent.field.filter(c => c.id !== 22) } },
  { id: 24, name: "Центровые", type: "normal", effect: (s) => { s.opponent.cring += s.me.field.some(c => c.id === 25) ? 25 : 12 } },
  { id: 25, name: "Берцы", type: "active", onTurnStart: (s) => { if (!s.me.field.some(c => c.id === 24)) { s.me.mental += 4; s.opponent.cring += 3 } } },
  { id: 26, name: "Пачка сигарет", type: "active", onTurnStart: (s) => { const bonus = Math.min(20, s.storiesPlayed * 2); s.me.mental += bonus } },
  { id: 27, name: "Расстрелять", type: "instant", effect: (s) => { const pack = s.opponent.field.find(c => c.id === 26); if (pack) { const stolen = Math.min(20, s.storiesPlayed * 2); s.me.mental += 6 + stolen * 2; } } },
  { id: 28, name: "Помойное ведро", type: "story", isStory: true, cring: 12, mental: 5 },
  { id: 29, name: "Чёрный кошелёк", type: "story", isStory: true, cring: 18 },
  { id: 30, name: "Нефоры и их истории", type: "story", isStory: true, effect: (s) => { s.opponent.cring += 6 + s.storiesPlayed * 4 } },
  { id: 31, name: "Похер, танцуй", type: "instant", effect: (s) => { s.me.protectedTurn = true } },
  { id: 32, name: "Батя в здании", type: "instant", mental: 15, effect: (s) => { s.opponent.ignoreEffects = true } },
  { id: 33, name: "Котлеты с пюрешкой", type: "normal", mental: 30, effect: (s) => { s.me.skippedTurn = true } },
  { id: 34, name: "Да мне пох, я на гидре", type: "instant", effect: (s) => { s.me.ignoreEffects = true } },
  { id: 35, name: "Шаверма после алко", type: "normal", mental: 15, cring: 10 },
  { id: 36, name: "Ты чё, самый умный?", type: "instant", effect: (s) => { if (s.opponent.hand.length > 0) s.opponent.hand.splice(Math.floor(Math.random() * s.opponent.hand.length), 1) } },
  { id: 37, name: "Приоры на минималках", type: "normal", effect: (s) => { s.opponent.cring += s.opponent.mental < 50 ? 20 : 10 } },
  { id: 38, name: "Зуб за зуб", type: "active", onTurnStart: (s) => { /* реализация через хук в game page */ } },
  { id: 39, name: "Сигма самец", type: "active", effect: (s) => { s.me.cring += 4 } },
  { id: 40, name: "Плаки-плаки", type: "instant", effect: (s) => { s.opponent.skippedTurn = true } },
  { id: 41, name: "Я щас сдохну", type: "instant", effect: (s) => { if (s.me.mental <= 40) s.opponent.cring += 40 } },
  { id: 42, name: "Кушать подкаст", type: "active", onTurnStart: (s) => { s.me.mental += 4 }, effect: (s) => { s.me.skippedTurn = true } },
  { id: 43, name: "Бери шмотки и вали", type: "instant", effect: (s) => { if (s.opponent.field.length > 0) s.opponent.field.splice(Math.floor(Math.random() * s.opponent.field.length), 1) } },
  { id: 44, name: "Теракт в метро", type: "normal", effect: (s) => { s.me.cring += 20; s.opponent.cring += 20 } },
  { id: 45, name: "Пацаны с раёна", type: "story", isStory: true, effect: (s) => { s.opponent.cring += 15 + (s.me.field.some(c => c.id === 24 || c.id === 25) ? 5 : 0) } },
  { id: 46, name: "Дед инсайд", type: "instant", mental: 100, effect: (s) => { setTimeout(() => { if (!s.winner) s.winner = s.opponent.userId }, 12000) } },
  { id: 47, name: "Это база", type: "instant", effect: (s) => { /* копирует последнюю карту оппонента — реализация в game page */ } },
  { id: 48, name: "Мажор на Гелике", type: "normal", effect: (s) => { s.opponent.cring += s.opponent.mental > 80 ? 25 : 8 } },
  { id: 49, name: "Я в домике", type: "instant", effect: (s) => { s.me.protectedTurn = true } },
  { id: 50, name: "Борщ с салом", type: "normal", mental: 35 },
  { id: 51, name: "Слово пацана", type: "active", effect: (s) => { s.me.protectedTurn = true; s.opponent.protectedTurn = true } },
  { id: 52, name: "Оливье 31 декабря", type: "story", isStory: true, cring: 20 },
  { id: 53, name: "Пацан к успеху шёл", type: "instant", effect: (s) => { for (let i = 0; i < 3; i++) s.me.deck.length && s.me.hand.push(s.me.deck.shift()!) } },
  { id: 54, name: "ТикТок Хаус", type: "active", isStory: true, onTurnStart: (s) => { /* +2 к каждой истории — реализация в эффектах */ } },
  { id: 55, name: "Жиза", type: "normal", effect: (s) => { if (s.storiesPlayed >= 5) s.opponent.cring += 35 } },
  { id: 56, name: "Бабушкин компот", type: "normal", mental: 20, effect: (s) => { s.opponent.mental += 20 } },
  { id: 57, name: "Я устал, я ухожу", type: "instant", effect: (s) => { /* завершает ход оппонента — реализация в game page */ } },
  { id: 58, name: "Го в мак", type: "normal", cring: 15, effect: (s) => { s.opponent.skippedTurn = true } },
  { id: 59, name: "Это не я, это мой брат", type: "instant", effect: (s) => { /* редирект кринжа — реализация в game page */ } },
  { id: 60, name: "Легендарный \"О нет, в любом случае\"", type: "instant", effect: (s) => { s.opponent.cring += 20 } },
]